# Generated by packaging/homebrew/render-cask.sh from axon.rb.tmpl.
# CI writes this file to matrix-axon/homebrew-tap on a version tag.
# Edit the template in matrix-axon/matrix-axon, not the generated tap copy.
cask "axon" do
  version "0.1.7"
  sha256 "6526381b0a596aec73e96b5002a9b9e6d2004ac2b2a3ff9fab49e75ec5a697e5"

  # The universal disk image from desktop-build.yml.
  url "https://github.com/matrix-axon/matrix-axon/releases/download/v0.1.7/Axon_0.1.7_universal.dmg"
  name "Axon"
  desc "Native desktop client for a self-hosted Axon server"
  homepage "https://github.com/matrix-axon/matrix-axon"

  # Tags, not releases/latest: a beta-*/alpha-* GitHub Release is not marked
  # prerelease, so "latest" can be a beta. The regex admits vX.Y.Z only.
  livecheck do
    url "https://github.com/matrix-axon/matrix-axon.git"
    regex(/^v(\d+(?:\.\d+)+)$/i)
  end

  # A client, not the server. Do not depend on the axon-server formula:
  # the server is often on another machine.
  # :high_sierra is macOS 10.13, Tauri's default minimumSystemVersion.
  # The iOS bundle's minimumSystemVersion is a different target.
  depends_on macos: ">= :high_sierra"

  app "Axon.app"

  zap trash: [
    "~/Library/Application Support/org.matrixaxon.axon",
    "~/Library/Caches/org.matrixaxon.axon",
    "~/Library/WebKit/org.matrixaxon.axon",
    "~/Library/Saved Application State/org.matrixaxon.axon.savedState",
  ]

  caveats <<~EOS
    Axon is the desktop client. It does not install or run axon-server.
    On first launch, enter the URL of an Axon server you already have.
    A local Homebrew axon-server listens on http://127.0.0.1:8080.
    The disk image is signed and notarized when the desktop release workflow had the Apple signing secrets.
    Without them, Gatekeeper blocks the app on first launch.
  EOS
end
