# Generated by packaging/homebrew/render-formula.sh from axon-tui.rb.tmpl.
# CI writes this file to matrix-axon/homebrew-tap on a version tag.
# Edit the template in matrix-axon/matrix-axon, not the generated tap copy.
class AxonTui < Formula
  desc "Terminal client for a self-hosted Axon server"
  homepage "https://github.com/matrix-axon/matrix-axon"
  license "Apache-2.0"
  version "0.1.8"

  # Checksums are of the GitHub Release zips from cross-build.yml, not a
  # source build. Asset names are part of that workflow's contract.
  on_macos do
    on_arm do
      url "https://github.com/matrix-axon/matrix-axon/releases/download/v0.1.8/axon-tui-macos-silicon.zip"
      sha256 "8d0042e56d5493989a4b5e9b5b35bacc188f872bc7cb0df56ad1a641c769df21"
    end
    on_intel do
      url "https://github.com/matrix-axon/matrix-axon/releases/download/v0.1.8/axon-tui-macos-intel.zip"
      sha256 "b00aa71d5116f16bd170e6040e0294c90538a88b47907223d903fa9c14f8e7a2"
    end
  end

  # Linux arm64 has no release zip. The url stays unconditional on Linux:
  # with no url at all, Homebrew stops at "requires at least a URL" before
  # depends_on arch: can explain.
  on_linux do
    depends_on arch: :x86_64

    url "https://github.com/matrix-axon/matrix-axon/releases/download/v0.1.8/axon-tui-linux.zip"
    sha256 "3c8afbe95e9220aa4b61844ef43d24af004b2491454e534606b2cfbc3eedb21d"
  end

  # A client, not the server. Do not depend on the axon-server formula:
  # the server is often on another machine. Do not declare a service.

  # Tags, not releases/latest: a beta-*/alpha-* GitHub Release is not marked
  # prerelease, so "latest" can be a beta. The regex admits vX.Y.Z only.
  livecheck do
    url "https://github.com/matrix-axon/matrix-axon.git"
    regex(/^v(\d+(?:\.\d+)+)$/i)
  end

  def install
    bin.install "axon-tui"
    doc.install "LICENSE.md"
    doc.install "THIRDPARTY"
  end

  def caveats
    text = <<~EOS
      axon-tui is a terminal client. It does not run the Axon server.
      Point it at an axon-server you already have. With no URL set, it
      uses http://127.0.0.1:8080, which is where a local Homebrew
      axon-server listens.

      The server URL and bearer token are read from this file on macOS
      and on Linux. The TUI does not use ~/Library/Application Support:
        ~/.config/axon-tui/config.toml

        [server]
        base_url = "http://127.0.0.1:8080"
        bearer_token = "<token printed by axon-server init>"

      `--base-url` and `--token` override that file for one run, as do
      AXON_BASE_URL and AXON_TOKEN. Prefer the config file for the token
      so it is not stored in your shell history.
    EOS
    if OS.linux?
      text += <<~EOS

        This Linux binary is the GitHub Release zip built on ubuntu-latest.
        A missing GLIBC symbol means the host is older than that zip.
      EOS
    end
    text
  end

  test do
    # axon-tui has no --version flag. --help exits 0 and names itself.
    assert_match "Usage: axon-tui", shell_output("#{bin}/axon-tui --help")
  end
end
